services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    networks:
      - backfront
      - backend-db

  backend-db:
    image: postgres:17
    container_name: backend-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${POSTGRES_USER:?}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:?}"
      POSTGRES_DB: "${POSTGRES_DB:?}"
    volumes:
      - "backend-db:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
      start_interval: 10s
    networks:
      - backend-db

volumes:
  backend-db:

networks:
  backend-db:
    name: backend-db
    internal: true
