spring.datasource.url=jdbc:sqlite:./data/petgram.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=petgram-backend

app.jwt.secret=petgram-dev-secret-change-this-to-32-bytes-minimum
app.jwt.expiration-minutes=120
